export default {
	was_home: (fixture) => fixture.was_home,
	opponent_team: (fixture) => fixture.opponent_team,
	total_points: (fixture) => fixture.total_points,
	team_h_score: (fixture) => fixture.team_h_score,
	team_a_score: (fixture) => fixture.team_a_score,
	round: (fixture) => fixture.round,
	minutes: (fixture) => fixture.minutes,
	goals_scored: (fixture) => fixture.goals_scored,
	assists: (fixture) => fixture.assists,
	clean_sheets: (fixture) => fixture.clean_sheets,
	goals_conceded: (fixture) => fixture.goals_conceded,
	own_goals: (fixture) => fixture.own_goals,
	penalties_saved: (fixture) => fixture.penalties_saved,
	penalties_missed: (fixture) => fixture.penalties_missed,
	yellow_cards: (fixture) => fixture.yellow_cards,
	red_cards: (fixture) => fixture.red_cards,
	saves: (fixture) => fixture.saves,
	bps: (fixture) => fixture.bps,
	value: (fixture) => fixture.value,
	selected: (fixture) => fixture.selected
}
