export type PastFixture = {
	was_home: boolean
	opponent_team: number
	total_points: number
	team_h_score: number
	team_a_score: number
	round: number
	minutes: number
	goals_scored: number
	assists: number
	clean_sheets: number
	goals_conceded: number
	own_goals: number
	penalties_saved: number
	penalties_missed: number
	yellow_cards: number
	red_cards: number
	saves: number
	bps: number
	value: number
	selected: number
	element: number
	fixture: number
	kickoff_time: string
	bonus: number
	influence: string
	creativity: string
	threat: string
	ict_index: string
	starts: number
	expected_goals: string
	expected_assists: string
	expected_goal_involvements: string
	expected_goals_conceded: string
	transfers_balance: number
	transfers_in: number
	transfers_out: number
}
